pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }

    environment {
        SNAP_REPO = 'vprofile-snapshot'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'admin'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vpro-maven-central'
        NEXUSIP = '172.31.1.40'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredential = 'ecr:eu-west-3:awscreds'
        appregistry = "956871201533.dkr.ecr.eu-west-3.amazonaws.com/vprofileappimages"
        vprofileRegistry = "https://956871201533.dkr.ecr.eu-west-3.amazonaws.com"
        cluster = 'vproprod'
        service = 'vproappprodsvc'
    }


    stages {
        stage('Deploy to ECS staging'){
            steps{
                withAWS(credentials: 'awscreds', region: 'eu-west-3'){
                   sh"aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }

        }
    }
}
